server:
  port: 8091
spring:
  profiles:
    active: dev

---

server:
  port: 8092
spring:
  profiles: dev
person:
  name: 哈哈
  age: 18
  boss: true
  date: 2020/01/01
  maps: {k1: v1, k2: 12}
  lists:
    - ll
    - aa
  dog:
    name: xx
    age: 1

---

server:
  port: 8093
spring:
  profiles: prod
