#
#debug: true

#
logging:
  level:
    cn.parzulpan.mapper: debug

spring:
  # 配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dockerT?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  # 配置 Redis
  redis:
    host: localhost

# MyBatis 设置
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名



